---
title: "Untitled"
author: "Emma Chen"
date: "3/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## package

```{r}
library(googlesheets4)
library(dplyr)
library(lubridate)
```

## Create object

```{r}
a <- 2
a = 2 # = 與 <-同義
```

```{r}
a
```

## name rule

###A valid variable name consists of:letters, numbers and the dot (.) or underline (_) characters.

###A variable name starts with:a letter;or the dot not followed by a number.
```{r}
my_108_total_credits <- 15
_108_total_credits <- 15
108_total_credits <- 15
_my_108_total_credits <- 15
my.108.total_credits <- 15
.108.total_credits <- 15 # 隱藏變數
.my.108.total_credits <- 15
我的108學年總學分數 <- 15
`我的108學年總學分數` <- 15 # 特殊名稱處理，`不是名稱的一部份
`.108.total_credits` <- 15
```

```{r}
`我的年紀` <- 20

`我的年紀`-> my_age
```

```{r}
`我的年紀`<-20

my_age<-`我的年紀`

'我的年紀'=20

my_age='我的年紀'

"我的年紀"<-20

My_age<-"我的年紀"

'我的年紀'<-20

my_age->20

我的年紀<-19

my_age<-我的年紀

```

```{r}
library(readr)
A02_company_all_public <- read_csv("https://www.dropbox.com/s/rtz2a9na62n3a8l/A02_company_all_public.csv?dl=1")
A02_company_all_public$`候選人` -> candidate
```

